### ISSUE TITLE
Problem with Config UI, nothing works anymore

### ISSUE THREAD

**Issue by Seexelas** [grzegorz914/homebridge-xbox-tv#160] opened 2023-02-22 11:53 UTC
Hi, 

As told in another post, since a few updates, nothing works anymore. I'm on Proxmox, with latest Homebridge and Node.JS and plugin vers. 2.8.3.

I just reloaded a fresh install with no backup restore and with just Xbox plugin installed, I have this : (Chrome or Edge same problem).

Config UI of plugin is broken : 

<img width="997" alt="image" src="https://user-images.githubusercontent.com/64669806/220611263-6443c8ed-f1dc-459d-8245-23522188c3ee.png">

If I put the config manually : 

"devices": [
                {
                    "name": "Xbox",
                    "host": "192.168.1.2",
                    "xboxLiveId": "FXXXXXXXXXXX",
                    "webApiControl": true,
                    "getInputsFromDevice": false,
                    "filterGames": false,
                    "filterApps": false,
                    "filterSystemApps": false,
                    "filterDlc": false,
                    "sensorPower": false,
                    "sensorInput": false,
                    "sensorScreenSaver": false,
                    "enableDebugMode": false,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "enableMqtt": false,
                    "mqttDebug": false,
                    "mqttAuth": false
                }
            ],
            "platform": "XboxTv"

I have this : 

When trying to authorize :

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/64669806/220612104-7f4849f1-be1b-409e-bec3-37c5dcb76912.png">

Or clean the token : 

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/64669806/220612021-37dc87eb-d9e1-41ef-94ac-6500d1f03a1a.png">

Without the Token, Xbox is reponding to Off / On command from Homebridge, or displaying where it is (Dashboard, Screensaver), 

Also, each time I click on config for the plugin and I'm not editing anything : 

<img width="440" alt="image" src="https://user-images.githubusercontent.com/64669806/220623086-2420e628-1680-4f03-a00b-cbed7e4f7df1.png">

Which is not normal. 

I don't know which log I must retrieve for you ?

Many thanks for the help :)

**Comment by grzegorz914** [comment] 2023-02-22 14:24
Please try 2.8.4 beta and let me know, open app after clean install need to be fixed now

**Comment by Seexelas** [comment] 2023-02-22 14:46
It's way better, thanks.

But webapi authorization not working : (plugin and config were removed and re added)

<img width="394" alt="image" src="https://user-images.githubusercontent.com/64669806/220657394-58586c87-dff6-4d97-be0d-454c8c4c8652.png">

**Comment by grzegorz914** [comment] 2023-02-22 15:05
Regarding clear web api token error I think app do not have permission to /var/lib/homebridge/xboxTv folder or permission are broken

**Comment by Seexelas** [comment] 2023-02-22 15:06
Weird because I did a full new wm install with iso of homebridge.

**Comment by Seexelas** [comment] 2023-02-22 15:09
<img width="1391" alt="image" src="https://user-images.githubusercontent.com/64669806/220663874-e661af38-2ba3-4f20-97c1-9b32ce386b22.png">

**Comment by grzegorz914** [comment] 2023-02-22 15:14
You don't have permission to the folder, check possibility write to the /homebridge/xboxTv/ folder

**Comment by Seexelas** [comment] 2023-02-22 15:15
<img width="538" alt="image" src="https://user-images.githubusercontent.com/64669806/220665873-cd47e804-e8ab-45b3-829b-5b28c3b337dc.png">

It's good no ? I don't see my issue :S sorry

**Comment by grzegorz914** [comment] 2023-02-22 15:16
Very strange, I cant this reproduce on my side.

**Comment by grzegorz914** [comment] 2023-02-22 15:18
any data in tokenFile?

**Comment by Seexelas** [comment] 2023-02-22 15:22
It seems empty, I deleted it and nothing changes. When I reboot instances, file is recreated. 

<img width="667" alt="image" src="https://user-images.githubusercontent.com/64669806/220667928-e50eaef3-a80a-4ddc-b204-00572f84c961.png">

**Comment by grzegorz914** [comment] 2023-02-22 15:34
Its correct, the file contain data after authorization done, If You start authorization in which step the error occurred?

**Comment by Seexelas** [comment] 2023-02-22 15:46
If I remove the file (or clean plugin install), I open the Config GUI, put the Xbox Name, IP, live ID. Save and restart. I open the config UI again, and then start authorization and I have this error : 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/64669806/220676213-22d0ec37-5b6e-4c53-9a51-d791d792ab99.png">

In the WebAPI plugin section : 

Email + Password in inserted.

**Comment by Seexelas** [comment] 2023-02-22 15:50
I found my WebApi token in an old backup. 

When I insert it into the configuration and restart : Homebridge says no token.

If I remove the file manualy and reboot : the same

**Comment by grzegorz914** [comment] 2023-02-22 15:57
email und password can be empty at this moment will be used in future, are you paste correct Live ID? from console settings?

**Comment by Seexelas** [comment] 2023-02-22 16:00
Yes, so I managed to get it working... so steps : 

- Put the old WebApi Token
- Restart
- Wait a bit
- Clean token -> Ok
- Authorize -> Ok
- Restart -> Still saying no token 
- Used the check auth -> Says ok
- Restart
- Now it's ok

I don't see that's ok in the logs, but I don't see anymore any errors.

**Comment by grzegorz914** [comment] 2023-02-22 16:03
then is no authorized, try beta 18 and get the output, I have added some debug more

**Comment by Seexelas** [comment] 2023-02-22 18:27
It's installed, what do you need ?

**Comment by Seexelas** [comment] 2023-02-22 18:30
I don't know what you changed, but now authToken_19216812 is populated : 

![image](https://user-images.githubusercontent.com/64669806/220723466-30aedae0-695d-4fac-b2dd-842e693354b8.png)

**Comment by Seexelas** [comment] 2023-02-22 18:36
But now : 
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/64669806/220725097-bbb2f6e1-91e1-44b9-a596-82e1484f2682.png">

Everything is setup right :S

**Comment by grzegorz914** [comment] 2023-02-22 18:47
Try 2.8.5-beta.0 and let me know

**Comment by Seexelas** [comment] 2023-02-22 19:16
Better, but still not authorized : 

<img width="1333" alt="image" src="https://user-images.githubusercontent.com/64669806/220735281-2291c31e-14c0-4066-8ffe-a2a5ff4852c4.png">

**Comment by grzegorz914** [comment] 2023-02-22 19:17
Try beta.3

**Comment by Seexelas** [comment] 2023-02-22 19:28
Yes ! Thanks so much.

It seems to work properly now :) 

There is just a bug when I select settings it goes to the dashboard. 

Many thanks

**Comment by grzegorz914** [comment] 2023-02-22 19:31
It’s not a bug, settings and some other inputs do not contain data to be set, In this case always spring to the dashboard but if you go t’o settings will display settings. So I close this as resolved.

**Closed by grzegorz914** 2023-02-22 19:31 UTC
